### ISSUE TITLE
Inbox Routing Use Phonebook kalkun 0.7.1 doesnt work

### ISSUE THREAD

**Issue by hmarina** [back2arie/Kalkun#114]
Hi, I am working with kalkun 0.7.1 and configure Inbox Routing Use Phonebook  in kalkun_settings.php  $config['inbox_routing_use_phonebook'] = TRUE; but it doesnt works no user including kalkun receive sms.

Anybody can helpme. the long my number in my country are 11 digits

Thank you.

HM

**Comment by sikasep23** [comment]
someone plz tell me how to enable inbox routing, i have try to chang config $config['inbox_routing_use_phonebook'] = TRUE; no effect, and try execute sql above i got empty result.. plz help
