### ISSUE TITLE
[tanya] kenapa inbox saya tidak terbaca di kalkun ya?

### ISSUE THREAD

**Issue by ardyutomo** [back2arie/Kalkun#125]
maaf mas..saya install kalkun 0.7.1. tapi inbox saya kosong. padahal di database mysql ada isinya. mohon solusinya

**Comment by firkanhartanto** [comment]
mas, mau tny... sy buat akun pengguna baru... tp pesan tidak keluar di inbox nya ? tp sy pake akun admin pertama sms bs muncul di inbox. sy liat2 ada tulisan "inbox master" apakah ada hubungannya dg itu ya ? kl smisal ada tdk ya cara spy inbox bs dibaca oleh user lain. Sy sdh mencoba buka di file php di folder config & database kalkun, blm ktmu cara nya... Terima kasih
