### ISSUE TITLE
Cannot Install Plugin

### ISSUE THREAD

**Issue by djtechwork** [back2arie/Kalkun#126]
Saya menggunakan kalkun 0.7.1. Proses instalasi lancar. Masalahnya ketika saya coba install Plugin muncul error berikut:

A Database Error Occurred

Error Number: 1364

Field 'plugin_name' doesn't have a default value

INSERT INTO `plugins` (`plugin_system_name`) VALUES ('blacklist_number')

Error ini terjadi pada semua plugin...
Terima kasih atas bantuannya...

**Comment by antoub** [comment]
sepertinya perlu diubah dikit 
file : application/libraries/Plugins.php
line : 265
$this->_ci->db->insert('plugins', array('plugin_system_name' => $name));
menjadi 
line : 265
$this->_ci->db->insert('plugins', array(
'plugin_system_name' => $name,
'plugin_name'=>self::$plugins_pool[$name]['plugin_info']['plugin_name'],
'plugin_version'=>self::$plugins_pool[$name]['plugin_info']['plugin_version'],
'plugin_description'=>self::$plugins_pool[$name]['plugin_info']['plugin_description'],
'plugin_author'=>self::$plugins_pool[$name]['plugin_info']['plugin_author'],
'plugin_author_uri'=>self::$plugins_pool[$name]['plugin_info']['plugin_author_uri']));
