### ISSUE TITLE
"A Database Error Occurred"

### ISSUE THREAD

**Issue by N3bTcx** [back2arie/Kalkun#140]
Hello

I'm using the last version of Kalkun on a fresh Raspbian. 

I'm getting the issue related to _Database Error_

```
A Database Error Occurred

Unable to connect to your database server using the provided settings.
```

I've enable the `error_reporting(E_ALL);`

No error on apache. When I connect on `index.php` log tell me.
`192.168.0.181 - - [04/Jan/2014:10:55:30 +0000] "GET / HTTP/1.1" 500 621 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:25.0) Gecko/20100101 Firefox/25.0"`

I've follow [Kalkun Installtion Wiki](https://github.com/back2arie/Kalkun/wiki/Installation) and create the database and Kalkun user. 

My `database.php`

```
$db['default']['hostname'] = "localhost";

// MySQL
$db['default']['username'] = "kalkun";
$db['default']['password'] = "******";
$db['default']['database'] = "kalkun";
$db['default']['dbdriver'] = "mysql";
```

And database in mysql

```
$ ~ mysql -u kalkun -p
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| kalkun             |
+--------------------+
2 rows in set (0.01 sec)
```

Don't understrand where I'm wrong.

**Comment by yuryja** [comment]
Hi, i have the same issue and cannot solve it... any idea?

**Comment by kocrex** [comment]
I'v got the same error.  any idea?

**Comment by kabili207** [comment]
In case anyone stumbles upon this error, I fixed it by changing the `dbdriver` setting from `mysql` to `mysqli`.

**Comment by kabili207** [comment]
Okay, it turned out to be a little more difficult than that. I also had to edit the `get_database_property($driver)` method in `application/helpers/kalkun_helper.php`. Add `mysqli` to the `$valid_driver` array, and then add the following below the existing calls.

```php
$mysqli['name'] = 'mysqli';
$mysqli['file'] = 'mysqli';
$mysqli['human'] = 'MySQLi';
$mysqli['escape_char'] = '`';
$mysqli['driver'] = 'mysqli';
```

After that, go to the directory `media/db` and copy the existing mysql scripts to ones with mysqli in the name.

**Comment by kingster** [comment]
Now supported via #187
