### ISSUE TITLE
daemon.sh in remote server

### ISSUE THREAD

**Issue by yuryja** [back2arie/Kalkun#159]
Hi, i'm trying to use Kalkun using the following configuration:
Gammu-smsd (local server)
Kalkun (Remote server)

i'm a VPS and verfied all permissions, routes of daemon.php and daemon.sh
gammu log says error 127

And 
runonreceive = http://url-my-vps/kalkun/scripts/daemon.sh
Can i use this configuration? What can i do?

**Comment by kingster** [comment]
I don't thik that you can run a remote url on runonreceive.

runonreceive must point to an local executable file on gammu-server, which should do the remote call on the kalkun server.
