### ISSUE TITLE
No DeliveryDateTime in DB while DeliveryReport present in log file.

### ISSUE THREAD

**Issue by whitehunter** [back2arie/Kalkun#163]
Hi, I have trouble with delivery reports. Column DeliveryDateTime.sentitems in DB backend always is NULL while incoming SMS works fine and log file has "Delivery report: Delivered to... ".
I try to reinstall everything but still don't work. 
I expected that the problem with SMSC numbers. In DB i see different SMSC number for incoming and outputting SMS. I try to set one of this in gamma-smsdrc (with this option: SMSC = +7...) but no affecting.

sorry of my english

**Comment by kingster** [comment]
Probably related to #154.

Closing this as this is seems to be a duplicate.
