### ISSUE TITLE
Installation troubles when using nginx

### ISSUE THREAD

**Issue by mohamnag** [back2arie/Kalkun#165]
I'm trying to setup Kalkun on a machine which has PHP and nginx and an already running gammu-smsd with existing database. 

The process I have followed is from the (wiki page)[https://github.com/back2arie/Kalkun/wiki/Installation] but after changing the DB settings on Kalkun, entering this URL `http://localhost/` redirects to `http://localhost/index.php/login` instead of installation. Even when I enter `http://localhost//index.php/install` I only get "404 not found" from nginx. This part is a problem with nginx setup and there is no instructions on installation page how this should be fixed.

Entering `http://localhost//index.php?install` also gives me `Installation disabled.` in browser. 

Entering `http://localhost//index.php?login` gives me the login page but I can not login.

**Comment by kingster** [comment]
Try manual installation step, since it seems that something is interfering with automated install.

**Comment by mohamnag** [comment]
the only "manual install" that I find is the step of importing schema into DB. In my case this is already done! gammu-smsd is working fine without kalkun. now what else kalkun needs to work properly?

also this not working routings are killing me, do you know specific settings for nginx which can fix it?

**Comment by kingster** [comment]
You would need to import the kalkun specific db sql also. 

I haven't tried with nginx, but all you need to do is route all requests to index.php, that should work.

**Comment by natsu90** [comment]
Hi @mohamnag, did you get this working? I got the same problem.

**Comment by mohamnag** [comment]
@natsu90, actually no! I gave up on using kalkun and wrote a simple PHP script myself, that was enough for me.

**Comment by kingster** [comment]
`Installation disabled` would mean that the `install` file or folder is missing, which is the step 1 of installation. For now I have added the file by default while downloading so that the setup starts with it. 

Closing this issue for now. Please reopen if you still face issue.
