### ISSUE TITLE
Kalkun on receive from number X, execute bash script ?

### ISSUE THREAD

**Issue by demogorgonz** [back2arie/Kalkun#166]
Hello,

Is there a way to call bash script if the message is received from number +XXXXXXXX for example and with content "do action 1" ?  :)

**Comment by kingster** [comment]
There are 2 ways

1. You create a new plugin and configure per number wise what to trigger and what to do
2. You can modify your run-on-recieve script to do the additional functionalities after checking the numbers and others.

**Comment by demogorgonz** [comment]
Hello @kingster , do you maybe have some example of script/plugin?

**Comment by kingster** [comment]
You can find the current supported plugins here : https://github.com/back2arie/Kalkun/tree/master/application/plugins

Regarding script, the current script just triggers kalkun's message-received trigger : https://github.com/back2arie/Kalkun/blob/master/scripts/daemon.sh

You can add your custom login after that, or add a new plugin, which would be automatically called by kalkun when a new message arrives.

**Comment by demogorgonz** [comment]
Thank you :) i'll try to make it .
