### ISSUE TITLE
what is PRIORITY in parameter -> add_action(HOOK_NAME, FUNCTION_NAME, PRIORITY);

### ISSUE THREAD

**Issue by navotera** [back2arie/Kalkun#169]
hi. sorry for asking this. 
what is the PRIORITY mean  in the action add_action(HOOK_NAME, FUNCTION_NAME, PRIORITY) ?

Is PRIORITY mean any incoming sms (for instance if i listening the incoming event) and extracted to single row() ?

Thanks

**Comment by kingster** [comment]
Read about how to write your plugin https://github.com/back2arie/Kalkun/wiki/Howto-write-plugin
