### ISSUE TITLE
kalkun shows disconnected

### ISSUE THREAD

**Issue by rajbps** [back2arie/Kalkun#170]
HI Team,

Installed kalkun on a vm and host is proxmox and did a usb passthroug.It all works fine until kalkun is not used for a few hours, the on the top screen it says disconnected.
Anly way to get it to work again is reboot the vm.

Any ideas or if more info is needed.please.

vm is ubuntu 15.10

Regards,

Raj

**Comment by kingster** [comment]
Kalkun talks with [Wammu](http://wammu.eu/smsd/), and this seems like issue with that. You can try raising the issue on their forums.
