### ISSUE TITLE
Disallowed Key Characters

### ISSUE THREAD

**Issue by quiricada** [back2arie/Kalkun#174]
for phone numbers starting with a plus sign eg. +15675551212

this function kicks in kalkun/system/libraries/input.php
function _clean_input_keys($str)
    {
        if ( ! preg_match("/^[a-z0-9:_\/-]+$/i", $str))
        {
            exit('Disallowed Key Characters.');
        }
        return $str;
    }

modified this statement
if ( ! preg_match("/^[a-z0-9:_\/-]+$/i", $str))
to
if ( ! preg_match("/^[a-z0-9:_\/-+]+$/i", $str))

added the + (plus sign) to the regular expression

**Comment by kingster** [comment]
Unable to replicate this on current devel. Please check again

This is when adding a user to phonebook.
![image](https://user-images.githubusercontent.com/709368/80483716-2a78e880-8974-11ea-9911-a10c4afbec7b.png)
