### ISSUE TITLE
Configure Kalkun using apache2

### ISSUE THREAD

**Issue by PiyushChaudhari** [back2arie/Kalkun#176]
Hello Team, 

Hope you are doing well. I am new for **Kalkun Open Source Web-based SMS Management**. I want to use **Kalkun Open Source Web-based SMS Management** I have read Requirement using **https://github.com/back2arie/Kalkun** which describe kalkun **configuration using xampp**. I want to configure **kalkun with apache2**. I don't have much idea to configure kalkun with apache2 so any one **help me to configure kalkun with apache2** or provide link me which will help me to configure kalkun with apache2.

**Comment by kingster** [comment]
Hope you were able to follow the readme and install the application. Incase you have still issues, please reopen with the error that you are getting.
