### ISSUE TITLE
PHP Warning:  fopen(http://localhost/sms/index.php/daemon/message_routine/)

### ISSUE THREAD

**Issue by SasaB14** [back2arie/Kalkun#177]
Hi,

i have everything setup on Ubuntu and MySQL and everything works fine but I keep getting following warning in log file:

Tue 2017/02/28 12:04:13 gammu-smsd[3105]: Warning: No PIN code in /etc/gammu-smsdrc file
Tue 2017/02/28 12:04:13 gammu-smsd[3107]: Connected to Database: sms on localhost
Tue 2017/02/28 12:04:13 gammu-smsd[3107]: Connected to Database native_mysql: sms on localhost
Tue 2017/02/28 12:04:13 gammu-smsd[3107]: Created POSIX RW shared memory at 0x7f0ad927a000
Tue 2017/02/28 12:04:13 gammu-smsd[3107]: Starting phone communication...
Tue 2017/02/28 12:04:18 gammu-smsd[3107]: Inserting phone info
Tue 2017/02/28 12:04:19 gammu-smsd[3107]: Read 1 messages
Tue 2017/02/28 12:04:19 gammu-smsd[3127]: Starting run on receive: /var/www/html/sms/scripts/daemon.sh 48
Tue 2017/02/28 12:04:19 gammu-smsd[3107]: Process finished successfully
**Tue 2017/02/28 12:04:19 gammu-smsd[3107]: Subprocess output: PHP Warning:  fopen(http://localhost/sms/index.php/daemon/message_routine/): failed to open stream: HTTP request fai$
 in /var/www/html/sms/scripts/daemon.php on line 8
PHP Stack trace:
PHP   1. {main}() /var/www/html/sms/scripts/daemon.php:0
PHP   2. fopen() /var/www/html/sms/scripts/daemon.php:8
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/html/sms/scripts/daemon.php on line 8
PHP Stack trace:
PHP   1. {main}() /var/www/html/sms/scripts/daemon.php:0
PHP   2. fclose() /var/www/html/sms/scripts/daemon.php:8**

my daemon.sh looks like this:
#!/bin/sh

PHP=/usr/bin/php # php cli path
DAEMON=/var/www/html/sms/scripts/daemon.php # daemon.php path

$PHP $DAEMON

my daemon.php looks like this:
<?php
// Make sure it's run from CLI
if(php_sapi_name() != 'cli' && !empty($_SERVER['REMOTE_ADDR'])) exit("Access Denied."); 

// Please configure this
$url = "http://localhost/sms";

fclose(fopen($url."/index.php/daemon/message_routine/", "r"));

?>

and my gammu-smsdrc:

[gammu]
port = /dev/ttyUSB1
connection = at
logformat = textall

[smsd]
service = sql
driver = native_mysql
logfile = /home/sasa/kalkun_log
Increase for debugging information
debuglevel = 0

user = ***
password = ***
pc = localhost
database = sms
runonreceive = /var/www/html/sms/scripts/daemon.sh

Paths where messages are stored
inboxpath = /var/spool/gammu/inbox/
outboxpath = /var/spool/gammu/outbox/
sentsmspath = /var/spool/gammu/sent/
errorsmspath = /var/spool/gammu/error/

Also when I run message_routine in browser I get following error:
A Database Error Occurred
Error Number: 1271

Illegal mix of collations for operation ' IN '

SELECT `token`, `count` FROM (`b8_wordlist`) WHERE `token` IN ('Hvala', 'Danas', 'će', 'biti', 'uplaćeno')

on server side allow_url_fopen is set to ON.
how can I avoid this issue?

**Comment by kingster** [comment]
Sorry for the super late reply!

This looks mostly permission error on php.ini. For now have replaced with `file_get_contents` so that output is also emitted.

Please reopen if issue is still present.
