### ISSUE TITLE
Error running Database setup

### ISSUE THREAD

**Issue by ScrumpyJack** [back2arie/Kalkun#179]
using the web install app, i get the following error after initial check are ok.
```A

 Database Error Occurred

Error Number: 1

table user_settings has 10 columns but 9 values were supplied

INSERT INTO "user_settings" VALUES (1, 'green', 'false;--\nPut your signature here', 'false', 20, 'true;background.jpg', 'default', 'english', 'asc');
```

This is a fresh sqlite3 database upgrade from a fresh gammu sqlite.db install. Gammu version 1.37.91

```
sqlite> select Version from gammu;
Version
16

sqlite> .schema user_settings
CREATE TABLE "user_settings" (
        "id_user" INTEGER PRIMARY KEY  NOT NULL, 
        "theme" VARCHAR(10) NOT NULL DEFAULT 'blue',
        "signature" VARCHAR(50) NOT NULL, 
        "permanent_delete" TEXT NOT NULL DEFAULT 'false', 
        "paging" INTEGER NOT NULL DEFAULT 10, 
        "bg_image" VARCHAR(50) NOT NULL,
        "delivery_report" TEXT NOT NULL DEFAULT 'default',
        "language" VARCHAR(20) NOT NULL DEFAULT 'english',
        "conversation_sort" TEXT NOT NULL DEFAULT 'asc',
        "country_code" VARCHAR(2) NOT NULL DEFAULT 'US',
        CHECK ("permanent_delete" IN ('true','false')),
        CHECK ("delivery_report" IN ('default','yes','no')),
        CHECK ("conversation_sort" IN ('asc','desc'))
);
```

looks like country_code is missing

Also the tables pbk and pbk_group have been removed from gammu.

```
ALTER TABLE "pbk" ADD COLUMN "id_user" INTEGER NULL;
ALTER TABLE "pbk" ADD COLUMN "is_public" TEXT NOT NULL DEFAULT 'false';

ALTER TABLE "pbk_groups" ADD COLUMN "id_user" INTEGER NULL;
ALTER TABLE "pbk_groups" ADD COLUMN "is_public" TEXT NOT NULL DEFAULT 'false';
```

The cause is here:
https://github.com/gammu/gammu/commit/6203631d6d4f4286d1b69033ba83a65b48484fff

Then, after adding country code and removing the pbk and pbk_groups ALTER statements
I get

```

A PHP Error was encountered
Severity: Warning
Message: Missing argument 2 for CI_DB_pdo_driver::_delete(), called in /var/www/html/system/database/DB_active_rec.php on line 1321 and defined
Filename: pdo/pdo_driver.php
Line Number: 529

A PHP Error was encountered
Severity: Notice
Message: Undefined variable: where
Filename: pdo/pdo_driver.php
Line Number: 531

A PHP Error was encountered
Severity: Warning
Message: implode(): Invalid arguments passed
Filename: pdo/pdo_driver.php
Line Number: 531

A Database Error Occurred
Error Number: 1
near " ": syntax error
DELETE FROM kalkun WHERE
```

Perhaps the pdo drivers need updating?

https://github.com/bcit-ci/CodeIgniter/tree/develop/system/database

**Comment by RPSPandora** [comment]
> Also the tables pbk and pbk_group have been removed from gammu.

Hi, if you're on windows, use older version of gammu. My setup works using Gammu 1.33.0.

**Comment by jlfsdtc** [comment]
Thank you,this my question too

**Comment by Alfadhly** [comment]
Hi
----
I have one problem :
I finished install Kalkun , and I opened it from browser (http://localhost/kalkun/)
but when  i make click on inbox it's go to error page (http://localhost/kalkun/index.php/messages/folder/inbox) .
----------------------------------

Error Number: 1146

Table 'kalkun.plugins' doesn't exist

SELECT * FROM (`plugins`) .
---------------------------------
please help me what can i do !!!!!!?

**Comment by kingster** [comment]
@Alfadhly did you follow the installation instructions? I just did a fresh installation from master and was able to setup completely.  Also missing table structs has been also added in the installation step. Do try and reopen the issue if you still face any issues. 

Please note that only mysql engine is updated to latest version and other engines yet needs to be updated.

**Comment by mr-media-creators** [comment]
A Database Error Occurred
Error Number: 1146

Table 'kalkun.b8_wordlist' doesn't exist

SHOW COLUMNS FROM `b8_wordlist`

Filename: C:/xampp/htdocs/Kalkun/vendor/codeigniter/framework/system/database/DB_driver.php

Line Number: 692
