### ISSUE TITLE
Enable mysqli in kalkun_helper.php to support PHP 7.x

### ISSUE THREAD

**Issue by jbubik** [back2arie/Kalkun#185]
Enable mysqli in application/helpers/kalkun_helper.php to support PHP 7.x.
The original mysql extension was removed from PHP 7.
Mysqli is supported by CodeIgniter, but needs some definitions in Kalkun.
I will open a pull request that solves this issue.

**Comment by kingster** [comment]
Hi @jbubik 

Were you able to get this working with 7.x ? If so, please do raise a PR so that other folks can also benefit from your contributions!

**Comment by kingster** [comment]
Supported with current master. Please try and let us know if you face any issues.
