### ISSUE TITLE
Table 'kalkun.plugins' doesn't exist 

### ISSUE THREAD

**Issue by Alfadhly** [back2arie/Kalkun#186]
Error Number: 1146

Table 'kalkun.plugins' doesn't exist

SELECT * FROM (`plugins`) .

**Comment by kingster** [comment]
Did you follow the installation instructions ?

`mysql kalkun - u username -p < media/db/mysql_kalkun.sql`

This steps creates the required tables. Please follow the installation instructions.

Kindly reopen the issue if you still face issue.
