### ISSUE TITLE
Don't work on el8

### ISSUE THREAD

**Issue by pavkamlc** [back2arie/Kalkun#189]
On CentOS 8 kalkun get HTTP error 500.
CentOS 8 provide in AppStream php versions 7.2 and newer. 
After install PHP 7.2 and enable error_reporting view a lot PHP errors.
[kalkun.txt](https://github.com/back2arie/Kalkun/files/3925625/kalkun.txt)

**Comment by kingster** [comment]
Please have a look at #187, this PR tries it make it compatible with php 7.2

**Comment by pavkamlc** [comment]
This code works... Thanks.
