### ISSUE TITLE
There is no available plugin.

### ISSUE THREAD

**Issue by lungaromark** [back2arie/Kalkun#198]
Installed successfully the latest version of Kalkun 0.7.1 on XAMPP. I am able to send and receive messages without any problems. However, no plugins are showing to install. Looked into the logs and there is no indication of any issues. 

Screenshot and logs are attached.

[log-2020-01-06.log](https://github.com/back2arie/Kalkun/files/4026875/log-2020-01-06.log)

![kalkun-plugins-issue](https://user-images.githubusercontent.com/6351862/71830208-8c040700-30a6-11ea-90c8-29c22fdf44bd.png)

**Comment by kingster** [comment]
The screenshot says that you are on the Installed plugins page, did you try clicking the "Available" button to see list of available plugins?

**Comment by lungaromark** [comment]
Yes, already did. Please find another screenshot.

![kalkun-plugins-issue-2](https://user-images.githubusercontent.com/6351862/71840016-c4164480-30bc-11ea-9b18-4c914226659f.png)

**Comment by lungaromark** [comment]
Is there a way how I can trouble shoot the issue to identify the problem?
