### ISSUE TITLE
An uncaught Exception was encountered

### ISSUE THREAD

**Issue by adidaya** [back2arie/Kalkun#206]
OS: Lubuntu 18.04
XAMPP: 7.2.0

I get an error when installing it:

```
An uncaught Exception was encountered
Type: Exception
Message: Configured database connection is persistent. Aborting.
Filename: /opt/lampp/htdocs/key/system/libraries/Session/drivers/Session_database_driver.php
Line Number: 94
```
How to solve it?

Thank you very much

**Comment by tenzap** [comment]
I already had this problem. I don't know why this has been changed in PR #192.
@pandigresik was that change necessary to fix the plugin issue ?
Same question for the change in $db['default']['hostname'] = "localhost";


In the meantime, to fix it, try changing in file application/config/database.php this line to FALSE
$db['default']['pconnect'] = FALSE;

**Comment by pandigresik** [comment]
> I already had this problem. I don't know why this has been changed in PR #192.
> @pandigresik was that change necessary to fix the plugin issue ?
> Same question for the change in $db['default']['hostname'] = "localhost";
> 
> In the meantime, to fix it, try changing in file application/config/database.php this line to FALSE
> $db['default']['pconnect'] = FALSE;

You're right, that is my mistake. I should not change it to true. Set it to false

**Comment by tenzap** [comment]
May you fix it in devel or make a PR please ?

**Comment by pandigresik** [comment]
> May you fix it in devel or make a PR please ?

I hope you can make pr to close this issue, please. For this time i can't make pr

**Comment by tenzap** [comment]
See PR #207 I completely reverted #192 since it is doesn't seem necessary to change the plugin path. The problem with plugins was they were not migrated to CI3. Migration of plugins is in PR #200 (hopefully soon merged)
