### ISSUE TITLE
Rest api still enabled after uninstall

### ISSUE THREAD

**Issue by john-arvid** [back2arie/Kalkun#228]
I wanted to test the rest api and the jsonrpc api with kalkun.
Installed both of them and tested. (rest api gave the 404, but there is a fix in dev for that, and json gave a code 0, but a new issue for that)
Uninstalled both of them and tested again, rest api still worked but jsonrpc was disabled as expected.

Using the latest master version of kalkun.

**Comment by kingster** [comment]
Please use devel branch and retest. Master branch currently has unknown issues.

**Comment by john-arvid** [comment]
Ok, it was not as straight forward to update so it could take some time.

**Comment by kingster** [comment]
Just changing branch and running "composer install" and removing "install" file  should be enough.

**Comment by kingster** [comment]
Please try with latest `devel`. Should be fixed by #231
