### ISSUE TITLE
In outbox, only 1st part of message is diplayed

### ISSUE THREAD

**Issue by tenzap** [back2arie/Kalkun#235]
Send a long message leading in at least 2 SMS.
Go to outbox, you will notice only the 1st part of the message is displayed
(when the message is in the sent items, all parts are here and the recepient receives the full message)

(DB: postgresql, don't know if this is also the case with mysql)

**Comment by kingster** [comment]
Same here, as further parts are on `outbox_multipart`. Needs fix in `Gammu_model.php`

**Comment by tenzap** [comment]
This is fixed in https://github.com/kalkun-sms/Kalkun.

Kalkun is now being maintained at a new home. Please head over to https://github.com/kalkun-sms/Kalkun for the latest version.
