### ISSUE TITLE
In compose window, Phonebook should be case insensitive

### ISSUE THREAD

**Issue by tenzap** [back2arie/Kalkun#237]
Add a contact in the phone book, let's say "John"
Now compose a message, and start typing "john" as recipient
It will not be found while one may expect it to be
If you type John, it gets found

**Comment by kingster** [comment]
Seems like case-sensitivity issue with your DB/Backend. With MySQL it works properly.

![image](https://user-images.githubusercontent.com/709368/80946593-02720500-8e0c-11ea-964f-ea49ad25940a.png)

**Comment by tenzap** [comment]
do you use "like" in the queries ? I known that for postgresql, like is case sensitive, while ilike is not.
(don't know about mysql)

**Comment by kingster** [comment]
```php
# Phonebook_model.php
function search_phonebook($param)	
	{
		$this->db->from('pbk');
		$this->db->select('Number as id');
		$this->db->select('Name as name');
		$this->db->where("({$this->_protect_identifiers('id_user')} = '{$param['uid']}'  OR {$this->_protect_identifiers('is_public')} = 'true' )");
		$this->db->like('Name', $param['query']);
		$this->db->order_by('Name');		
		return $this->db->get();
	}
```

Not sure if codeigniter has `ilike` support.

**Comment by tenzap** [comment]
That bug could happen on mysql too depending on collation.
Just as a reference : https://www.got-it.ai/solutions/sqlquerychat/sql-help/data-definition/how-to-do-a-case-sensitive-insensitive-search-in-mysql-querychat/

**Comment by tenzap** [comment]
Maybe overriding the like of CI with ilike can be the solution
suggested here: https://forum.codeigniter.com/thread-10697.html?highlight=ilike

**Comment by kingster** [comment]
That doesn't seem a possible solution since the system folder is now managed directly from upstream. Also changing any file in the system folder for any feature doesn't sound reasonable and prone to breakage during library upgrades. It should be somehow handled in the query/index maybe IMO.

**Comment by kingster** [comment]
Something like https://stackoverflow.com/a/25468642 should be a better solution.

**Comment by tenzap** [comment]
Wouldn't it be possible to override it form inside the application folder ?
Maybe with something like this ?
https://web-technos.blogspot.com/2013/01/codeigniter-tutorial-how-to-extend-helper-pluralization.html

**Comment by tenzap** [comment]
> Something like https://stackoverflow.com/a/25468642 should be a better solution.

Oh :)
