### ISSUE TITLE
Cannot add 2nd contact in phonebook

### ISSUE THREAD

**Issue by tenzap** [back2arie/Kalkun#238]
Go to phonebook
Click "Add contact"
Select "Using Contact Form"
The add contact form that gets displayed as a popup is empty (though it was correctly displayed when adding the 1st contact)

**Comment by kingster** [comment]
Didn't observe this issue.

![image](https://user-images.githubusercontent.com/709368/80944746-e40a0a80-8e07-11ea-8cef-abab7a0ffac0.png)

MySQL backend.

**Comment by tenzap** [comment]
Ok. I'm on postgreSQL
Now even adding a 1st contact is buggy.
Also according to your screenshot it seems you didn't need to create a group before, which was required for me.

Logs report this:
```
ERROR - 2020-05-04 09:48:49 --> Query error: ERREUR:  syntaxe en entrée invalide pour l'entier : «  »
LINE 3: WHERE "ID" = ''
                     ^ - Invalid query: SELECT *
FROM "pbk_groups"
WHERE "ID" = ''
AND "id_user" = '1'
```

**Comment by kingster** [comment]
No, I had to create a Group before otherwise, it didn't let me add.
