### ISSUE TITLE
Install without php-ctype is not checked

### ISSUE THREAD

**Issue by realJoshByrnes** [back2arie/Kalkun#264]
During install, some checks are made, and it's probably a good idea to check if php-ctype is available.

At present, after everything is shown "OK" (database_setup page) there is an error if php-ctype is not enabled

An uncaught Exception was encountered
Type: Error
Message: Call to undefined function ctype_digit()
Filename: /var/www/vendor/codeigniter/framework/system/database/DB_driver.php
Line Number: 1399

**Comment by kingster** [comment]
Resolved via #267
