### ISSUE TITLE
An uncaught Exception was encountered

### ISSUE THREAD

**Issue by Einaudij** [back2arie/Kalkun#278]
Hello,

While finalizing the installation of kalkun with the graphical web I got this error message:

![image](https://user-images.githubusercontent.com/18211152/148965164-3bc4bf28-3dac-41ed-86f8-14197827051a.png)

What prevents me from finalizing the config of the DB

Can you help me ?

Here is the content of Database_setup.php:

![image](https://user-images.githubusercontent.com/18211152/148965498-fed6da7c-69a0-4d9b-b9a1-5ad13cad8758.png)

I am in debian (11) bullseye

Requirements Checks : 

![image](https://user-images.githubusercontent.com/18211152/148965775-8b67d0ae-9509-4913-8bb2-015f12d6f084.png)

Best regards
Johnny

[database_setup.zip](https://github.com/kalkun-sms/Kalkun/files/7847518/database_setup.zip)

**Comment by tenzap** [comment]
try setting: `'install': ?>` instead of `'install' :?>`

ie, remove the space before the colon and add space after
