### ISSUE TITLE
Plugin "Server Alert" Database Error

### ISSUE THREAD

**Issue by oachkatzlschwaf** [back2arie/Kalkun#41]
Hi *!

I've installed the "server alert" plugin and i created the table "plugin_sever_alert" with "plugins/server_alert/media/mysql_server_alert.sql".

When clicking on the "Server Alert" link on the plugins-page in kalkun, i get the error:

> A Database Error Occurred
> 
> Error Number: 1146
> 
> Table 'kalkun.plugin' doesn't exist
> 
> SELECT `plugin_status` FROM (`plugin`) WHERE `plugin_name` = 'server_alert'

I think the problem comes with the FROM-clause in the sql statement. Correct table-name should be "plugins" ...

Best Regards

PS: i'm using kalkun 0.4.

**Comment by kgulle** [comment]
A Database Error Occurred
Error Number: 1146

Table 'kalkun.kalkun' doesn't exist

install error web url:http://localhost:8080/kalkun/index.php/install/run_install/install

**Comment by Alfadhly** [comment]
Hi
—-
I have one problem :
I finished install Kalkun , and I opened it from browser (http://localhost/kalkun/)
but when i make click on inbox it’s go to error page (http://localhost/kalkun/index.php/messages/folder/inbox) .
———————————-

Error Number: 1146

Table ‘kalkun.plugins’ doesn’t exist

SELECT * FROM (`plugins`) .
———————————
please help me what can i do !!!!!!?
