### ISSUE TITLE
Kalkun_API.php

### ISSUE THREAD

**Issue by MorfeiSYS** [back2arie/Kalkun#485]
Errors appear when executing example.php.
Stack trace:
#0 /var/www/htdocs/scripts/cURL/Kalkun_API.php(168): curl_setopt()
#1 /var/www/htdocs/scripts/cURL/Kalkun_API.php(85): Kalkun_API->get_csrf_hash_from_login_form()
#2 /var/www/htdocs/scripts/cURL/Kalkun_API.php(52): Kalkun_API->login()
#3 /var/www/htdocs/scripts/cURL/example.php(12): Kalkun_API->run()
#4 {main}
How to fix this error?

**Comment by tenzap** [comment]
Did you install the curl extension of php? Does your system meet the https://github.com/kalkun-sms/Kalkun/wiki/Requirements ?

Please, again, fill the issue template correctly.

**Comment by tenzap** [comment]
Closing since there has been no additional info provided.
