### ISSUE TITLE
Translation - norwegian

### ISSUE THREAD

**Issue by syvert68** [back2arie/Kalkun#486]
[norwegian.zip](https://github.com/kalkun-sms/Kalkun/files/10251738/norwegian.zip)
 Translation files for norwegian language. I've installed and use them on my own sms-gateway, and it seems to work fine. I haven't shared these kind of things before, so don't shoot me if I've done this the wrong way ;-)

**Comment by tenzap** [comment]
Thank you!

Did you ever try to make a [Pull Request](https://github.com/kalkun-sms/Kalkun/pulls)? Would you like to try? This would permit to keep authorship of your commits.

You might also want to add yourself to `docs/CREDITS` file.

**Comment by syvert68** [comment]
Hi!

I tried to make a Pull Request, mainly because I understood that it was the prefered way to do it.  However, probably because I’m to stupid or to noob, I didn’t manage to do that.  When I choose  «New Pull Request, I enter a site where I have to pick two items to compare.  The Button «Create pull requets» is disabled.  When I do that, I either get the message that there is nothing to compare, or a list of commits and the button to create pull request disappear.  As I said, I’m totally new to this, so it’s problably hilarious that I wasn’t able to do a simple task like this 😉, but I did try.

It’s not so important to me to get credits, but I hate it when I don’t understand something 😉.  I got the translation to work on my installation, and thought it couldn’t hurt to share it.

Med vennlig hilsen

Syvert Fossdal
Personal- og HMS ansvarlig

+47 901 78 872

***@***.******@***.***>

www.holbekanlegg.no

***@***.***

Postboks 193, 4703 Vennesla
Org.nr 997077806

Fra: tenzap ***@***.***>
Sendt: søndag 18. desember 2022 13:23
Til: kalkun-sms/Kalkun ***@***.***>
Kopi: Syvert Fossdal ***@***.***>; Author ***@***.***>
Emne: Re: [kalkun-sms/Kalkun] Translation - norwegian (Issue #486)


Thank you!

Did you ever try to make a Pull Request<https://github.com/kalkun-sms/Kalkun/pulls>? Would you like to try? This would permit to keep authorship of your commits.

You might also want to add yourself to docs/CREDITS file.

**Comment by tenzap** [comment]
To create a pull request, you need to fork the project, update the code on your fork. Then you can do it.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
