### ISSUE TITLE
Error on the dashboard in "Gammu state" field

### ISSUE THREAD

**Issue by heaveaxy** [back2arie/Kalkun#489]
Following exceptions shows in dashboard / gammu state field:
```
An uncaught Exception was encountered
Type: ErrorException

Message: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated

Filename: /var/www/Kalkun_v0.8.0_forPHP8.1/application/views/main/dashboard/home.php

Line Number: 34

Backtrace:

File: /var/www/Kalkun_v0.8.0_forPHP8.1/application/views/main/dashboard/home.php
Line: 34
Function: htmlentities

File: /var/www/Kalkun_v0.8.0_forPHP8.1/application/third_party/MX/Loader.php
Line: 352
Function: include

File: /var/www/Kalkun_v0.8.0_forPHP8.1/application/third_party/MX/Loader.php
Line: 295
Function: _ci_load

File: /var/www/Kalkun_v0.8.0_forPHP8.1/application/views/main/layout.php
Line: 35
Function: view

File: /var/www/Kalkun_v0.8.0_forPHP8.1/application/third_party/MX/Loader.php
Line: 352
Function: include

File: /var/www/Kalkun_v0.8.0_forPHP8.1/application/third_party/MX/Loader.php
Line: 295
Function: _ci_load

File: /var/www/Kalkun_v0.8.0_forPHP8.1/application/controllers/Kalkun.php
Line: 51
Function: view

File: /var/www/Kalkun_v0.8.0_forPHP8.1/www/index.php
Line: 315
Function: require_once
```
CI_ENV = development

- Kalkun version: Kalkun_v0.8.0_forPHP8.1
- Operating system: AlmaLinux 8.7, last updates
- PHP Version: 8.1.14
- DB Backend: 10.3.35-MariaDB
- Gammu version & DB Schema: 1.42.0
- Browser: Vivaldi 5.6
- Installed plugins: none

**Additional context**
![2023-01-31_16-23](https://user-images.githubusercontent.com/24751685/215720331-bc506aab-43ce-4fa4-9054-4fce14ff537a.png)

**Comment by heaveaxy** [comment]
Wow, I understood. This error shows only when gammu daemon is not connected to device.
So, from that pov it is not critical issue.

**Comment by kingster** [comment]
Thanks, but then this should be handled. I think this is an error that crept in during upgrades. Marking this issue as an bug.
