### ISSUE TITLE
License issue: `GPL-3-or-later` not compatible with `GPL-2-only`

### ISSUE THREAD

**Issue by tenzap** [back2arie/Kalkun#505]
Currently kalkun is licensed under `GPL-3-or-later`.
However, kalkun is closely bound to Gammu which is `GPL-2-only`.
Moreover, some of the code/files in kalkun is also under GPL2 license.

For example:
application/plugins/sms_to_twitter/libraries/Epi.php
application/plugins/sms_to_twitter/libraries/Twitter.php
application/sql/mysql/pbk_gammu.sql
application/sql/pgsql/pbk_gammu.sql
application/sql/sqlite/pbk_gammu.sql

The problem is that these licenses (`GPL-3-or-later` & `GPL-2-only`) are actually not compatible as per https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility

I think Kalkun was wrongly licensed under `GPL-3-or-later` because Gammu's license doesn't permit that.
I suggest to relicense kalkun under `GPL-2-or-later`.

I would agree with this, what do you think @kingster, @back2arie, @pandigresik ?

**Comment by kingster** [comment]
I think we need the agreement of @back2arie  in order to re-licence to `GPL-2-or-later`. @back2arie Maybe you could share your views since you are the original author of project?

**Comment by back2arie** [comment]
Dear All,

Yes, let's do that. I guess we can't help it since currently we are "bound" to Gammu.
I was not aware of the incompatibilities before, thanks for pointing that out.
