### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by aldhytrisnaldi** [back2arie/Kalkun#509]
<body>
	<div id="container">
		<h1>A Database Error Occurred</h1>
		<p>Error Number: 1054</p><p>Unknown column 'id_folder' in 'where clause'</p><p>SELECT *
FROM `inbox`
JOIN `user_inbox` ON `user_inbox`.`id_inbox`=`inbox`.`ID`
WHERE (`UDH` = '' OR `UDH` LIKE '%1')
AND `id_folder` = 1
AND `readed` = 'false'
AND `user_inbox`.`id_user` = '1'</p><p>Filename: C:/xampp/htdocs/sms-gateway/vendor/codeigniter/framework/system/database/DB_driver.php</p><p>Line Number: 692</p>	</div>
</body>

**Comment by aldhytrisnaldi** [comment]
and readed column not found

**Comment by tenzap** [comment]
Did you follow the installation instructions on the wiki? (all items of the Setup section)
Please give the details that were asked in the issue template, at least those that you can provide.

**Comment by aldhytrisnaldi** [comment]
Solved, Thankyou duded, i forgot one step to import another db xixixix
