### ISSUE TITLE
Problems to use the jsonrpc plugin

### ISSUE THREAD

**Issue by ovargasp** [back2arie/Kalkun#520]
I started using Kalkun a few days ago and it's really good, very simple to configure, a few minor things during installation but nothing you can't resolve with some reading, until I got to this jsonrpc API... Installation was really simple, but I don't know why I can't make it work, the resp_api installed and started working easily, but this json plugin I can't get it to work.

According to Kalkun wiki, the curl command to use it is: 
curl -X POST -H 'Content-Type: application/json' -i 'http://localhost/kalkun/index.php/plugin/jsonrpc/send_sms' --data '{"jsonrpc":"2.0","id":1,"method":"sms.send_sms","params":{"phoneNumber":"+123456789","message":"Testing JSONRPC"}}'

but as soon as I do that I get a message back saying: An Error Was Encountered, The action you have requested is not allowed.

And in the apache access log I get this: "POST /kalkun/index.php/plugin/jsonrpc/send_sms HTTP/1.1" 403 1489 "-" "curl/7.68.0"

No errors, nothing, I even enabled Kalkun debugging and still no errors,

If I use postman is the same thing just the access log message:
"POST /kalkun/index.php/plugin/jsonrpc/send_sms HTTP/1.1" 403 1506 "-" "PostmanRuntime/7.41.0"

everything else works perfectly, I can send messages from the Kalkun UI, use the resp_api to send messages as the wiki says, is just the jsonrpc plugin, and the problem that I have is that the other software that I'm using and I need to integrate with kalkun only uses json to comunicate, so any ideas will be appreciated.

This is my environment: 

System information
Operating system	:	Linux
Gammu version	:	Gammu 1.41.0, Linux, kernel 5.4.0-190-generic (#210-Ubuntu SMP Fri Jul 5 17:03:38 UTC 2024), GCC 9.2
Gammu DB schema	:	17
php version 8.1

installed pluggins:

jsonrpc version 1.0
rest_api version 0.1

I forgot to mention that I already checked file permits, for both resp_api and jsonrpc and they have the same file permits and owners

**Comment by ovargasp** [comment]
I think I found my answer, after some more time testing, reading and due the message "The action you have requested is not allowed." I decided to send a GET instead of a POST:

curl -X **GET** -H 'Content-Type: application/json' -i 'http://localhost/kalkun/index.php/plugin/jsonrpc/send_sms' --data '{"jsonrpc":"2.0","id":1,"method":"sms.send_sms","params":{"phoneNumber":"+123456789","message":"Testing JSONRPC"}}'

and I received this response: 
{"jsonrpc":"2.0","id":551,"result":"Message queued."} 

so its working just using a GET not a POST

**Comment by ovargasp** [comment]
Addding to it, by chance while trying to do figure out why POST is not valid, I typed in PUT instead of POST, and it also works... so this is also valid:

curl -X **PUT** -H 'Content-Type: application/json' -i 'http://localhost/kalkun/index.php/plugin/jsonrpc/send_sms' --data '{"jsonrpc":"2.0","id":1,"method":"sms.send_sms","params":{"phoneNumber":"+123456789","message":"Testing JSONRPC"}}'

**Comment by kingster** [comment]
Thanks for finding this bug and getting into the details. This looks like a small issue, we will get this fixed soon

**Comment by ovargasp** [comment]
Great thanks @kingster

**Comment by ovargasp** [comment]
One last post to close the issue: 

There is a consideration in codeigniter framework regarding **API endpoints expecting externally POSTed content**  aparently those need to be **whitelisted from CSRF protection** to work, so as soon as you do that, or disable csrf protection (that I don't recommend but is an option) the post requests will start working just the same as the get and put requests. Other options will require to code, and upgrade condeigniter version of kalkun if I'm not mistaken.

Here is the reference: https://codeigniter.com/user_guide/libraries/security.html#enable-csrf-protection

**Comment by ovargasp** [comment]
One last post to close the issue:

There is a consideration in codeigniter framework regarding **API endpoints expecting externally POSTed content** aparently those need to be **whitelisted from CSRF protection** to work, so as soon as you do that, or disable csrf protection (that I don't recommend but is an option) the post requests will start working just the same as the get and put requests. Other options will require to code, and upgrade condeigniter version of kalkun if I'm not mistaken.

Here is the reference: https://codeigniter.com/user_guide/libraries/security.html#enable-csrf-protection

**Comment by ovargasp** [comment]
One last post to close the issue:

There is a consideration in codeigniter framework regarding API endpoints expecting externally POSTed content aparently those need to be whitelisted from CSRF protection to work, so as soon as you do that, or disable csrf protection (that I don't recommend but is an option) the post requests will start working just the same as the get and put requests. Other options will require to code, and upgrade condeigniter version of kalkun if I'm not mistaken.

Here is the reference: https://codeigniter.com/user_guide/libraries/security.html#enable-csrf-protection
