### ISSUE TITLE
Multi user inbox problem 

### ISSUE THREAD

**Issue by fawwaz** [back2arie/Kalkun#98]
I've Installed Kalkun 0.6 and added several users. Some of those users have some mutual phone book number. Then i test the kalkun by sending some message to kalkun with the mutual phone number. The Next thing happen is the message does'nt appear in their inbox. Then I check  the database table 'inbox' and 'user_inbox'. the message is actually added to the table. 
Confusing with theese problem, i tried to delete an user. and when i check the 'user_inbox' table, the id_inbox and id_user is still being there. Is it a bug ?I'm newbie here. thanks a lot

**Comment by ErenRavenHeart** [comment]
I know i'm too late but I fixed this problem by replacing the php.exe path and the daemon path in these following files
-- daemon.bat
-- daemon.php 
thats all.. hope this helps :)
